
--Definición de roles y permisos

--CREATE ROLE USUARIODR;
GRANT EXECUTE ON PK_USUARIO2 TO USUARIO2;

--CREATE ROLE ADMINISTRADORDR;
GRANT EXECUTE ON PK_ADMINISTRADOR2 TO ADMINISTRADOR2;

--CREATE ROLE BIBLIOTECARIODR;
GRANT EXECUTE ON PK_BIBLIOTECARIO2 TO BIBLIOTECARIO2;
