--CICLO 2 : ACCIONES

ALTER TABLE Asistentes ADD CONSTRAINT FK_Asistentes_Evento FOREIGN KEY (idEvento) REFERENCES Eventos(id) ON DELETE CASCADE;
ALTER TABLE Asistentes ADD CONSTRAINT FK_Asistentes_Evento FOREIGN KEY (idEvento) REFERENCES Eventos(id) ON UPDATE CASCADE;
